export const CHANGE_TAB = 'CHANGE_TAB';
export const FETCH_CURRENT_WORKOUT = 'FETCH_CURRENT_WORKOUT';
export const FETCH_CURRENT_WORKOUT_COMPLETE = 'FETCH_CURRENT_WORKOUT_COMPLETE';
export const SET_EXECERCISE_VISIBILITY = 'SET_EXECERCISE_VISIBILITY';
export const ADD_EXERCISE = 'ADD_EXERCISE';
export const ADD_EXERCISE_COMPLETE = 'ADD_EXERCISE_COMPLETE';
